### ISSUE TITLE
I got this error 

### ISSUE THREAD

**Issue by hackingstar124** [capture0x/LFI-FINDER#5]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycrypto
  Running setup.py clean for pycrypto                                   
Failed to build pycrypto
ERROR: Could not build wheels for pycrypto, which is required to install pyproject.toml-based projects

**Comment by capture0x** [comment]
You can try this commands :
sudo apt-get update
sudo apt-get install python3-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev
sudo apt-get install python3.11-dev
pip install --upgrade pillow twisted pycrypto pycryptodome
